- name: Ensure essentials for NeoVim
  become: yes
  pacman: 
    name: 
      - git    
      - unzip  
      - wget   
      - make   
      - gcc    
      - ripgrep
    state: present

- name: Install NeoVim
  become: yes
  pacman:
    name: neovim
    state: present