- name: Import GPG Keys from Microsoft
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags: vscode

- name:  Install VSCode Repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  tags: vscode

- name: Update Packages List
  apt:
    update_cache: yes
  tags: vscode

- name: Instalar VSCode
  apt:
    name: code
    state: present
  tags: vscode
