- name: Install base-devel 
  become: yes
  pacman: 
    name: base-devel
    state: present
  tags: core

- name: Check if yay is installed
  ansible.builtin.command: pacman -Qs yay
  register: yay_installed
  ignore_errors: true
  tags: 
    - core
    - aur

- name: Download yay
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/yay-bin.git'
    dest: ~/yay-bin
    clone: yes
  when: yay_installed.rc != 0
  tags: 
    - core
    - aur

- name: Install yay
  ansible.builtin.shell: 
    cmd: makepkg -si --noconfirm
    chdir: ~/yay-bin
  args:
    executable: /bin/bash
  when: yay_installed.rc != 0
  tags: 
    - core
    - aur

# see: https://github.com/ibraheemdev/modern-unix
- name: Install GNU tools
  become: yes
  pacman:
    name: 
      - stow
      - fzf       # fuzzy finder
      - ripgrep   # grep
      - bat       # cat
      - btop      # top
      - eza       # ls
      - man-db
      - tldr      # man
      - gping     # ping 
      - hyperfine # benchmarking tool
      # - dust      # du (file-tree size) 
      # - duf       # df (file system manager)
      # - broot     # tree
      # - mcfly     # history
    state: present
  tags: core

# - name: Install `cheat` (cheatsheets)
#   become: yes
#   pacman: 
#     name: cheat # interactive cheatsheets
#     state: present
#     executable: yay 
#     extra_args: --builddir /var/cache/yay
#   tags: core