- name: Install Core Utils in Archlinux
  include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"
  tags: core

- name: Install Core Utils in Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: core
  
- name: Symlink git dotfiles
  shell: 'stow -d ~/.dotfiles/home/ -S git -t {{ ansible_env.HOME }} --verbose=2 --adopt'
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
  tags: 
    - core
    - git