- name: Install fnm
  shell: 'curl -fsSL https://fnm.vercel.app/install | bash'
  tags: node

- name: Source new fnm.fish file
  shell: 'fish /home/strange/.config/fish/conf.d/fnm.fish'
  tags: node

- name: Install nodejs Latest
  shell: 'fnm install --latest'
  args:
    executable: /bin/bash
  tags: node

# - name: Install Bun
#   shell: 'curl -fsSL https://bun.sh/install | bash'
#   tags: bun