- name: Install Nodejs in Archlinux
  include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"
  tags: node

- name: Install Nodejs in Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: node

- name: Install Nodejs in Windows
  import_tasks: windows.yml
  when: ansible_distribution == "Windows"
  tags: node