- name: Ensure git, base-devel
  become: yes
  pacman:
    name:
      - git
      - base-devel
    state: present
  when: ansible_distribution == "Archlinux"
  tags: aur

- name: Download yay-bin
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/yay-bin.git'
    dest: ~/yay
    clone: yes
  tags: aur

- name: Install yay
  ansible.builtin.shell: cd yay-bin & makepkg -si
  tags: aur
