
vars:
  dotfiles: "{{ lookup('env', 'HOME') }}/.dots/home"
  config: "{{ lookup('env', 'HOME') }}"

- name: Install Fish + Starship
  become: yes
  pacman:
    name:
      - fish
      - starship
    state: present
  when: ansible_distribution == "Archlinux"
  tags: fish

- name: Install Fish (Ubuntu)
  become: yes
  ansible.builtin.apt:
    name: fish
    state: present
  when: ansible_distribution == "Ubuntu"
  tags: fish

- name: Install Starship (non-Archlinux)
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: ~/.cargo/bin/starship
  when: ansible_distribution != "Archlinux"
  tags:
    - fish 
    - starship

- name: Setup Fish as default shell
  become: true
  shell: 'chsh -s $(which fish)'

- name: Symlink fish dotfiles
  shell: 'stow -d {{ dotfiles }}/fish -t ~/{{ config }}'

- name: Initialize Starship prompt for Fish
  lineinfile:
    path: ~/.config/fish/config.fish 
    line: 'starship init fish | source'
    create: yes
  tags: 
    - fish 
    - starship


