vars:
  source_key: "./ssh/id_rsa"
  dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

- name: Install openssh
  become: yes
  pacman:
    name: openssh
    state: present
  tags: ssh

- name: Enable ssh service
  become: yes
  ansible.builtin.systemd:
    name: sshd
    state: started
    enabled: yes
  tags: ssh

- name: Ensure .ssh directory exists.
  become: yes
  file: 
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags: ssh

- name: Install ssh key
  become: true
  copy: 
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags: ssh

- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  tags: ssh