- name: Install Hyprland
  become: yes
  pacman:
    name: hyprland # hyprland-nvidia-git if nvidia
    state: present
  tags: hyprland

# see: https://wiki.hyprland.org/Useful-Utilities/Must-have/#a-notification-daemon
- name: Install Notification Daemon (dunst)
  become: yes
  pacman: 
    name: dunst
    state: present
  tags: hyprland

# see: https://wiki.hyprland.org/Useful-Utilities/Must-have/#xdg-desktop-portal
- name: Install Desktop Portal (xdg-desktop-portal-hyprland)
  become: yes
  pacman: 
    name: xdg-desktop-portal-hyprland
    state: present
  tags: hyprland

# see: https://wiki.hyprland.org/Useful-Utilities/Must-have/#authentication-agent
- name: Install Authentication Agent (polkit-kde-agent)
  become: yes
  pacman: 
    name: polkit-kde-agent
    state: present
  tags: hyprland

- name: Install Qt Wayland Support
  become: yes
  pacman: 
    name: 
      - qt5-wayland
      - qt6-wayland
    state: present
  tags: hyprland

# see: https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#waybar
- name: Install Waybar
  become: yes
  pacman: 
    name: waybar
    state: present
  tags: hyprland


# see: https://wiki.hyprland.org/Useful-Utilities/App-Launchers/#rofi-wayland-fork
- name: Install App Launcher (rofi-wayland)
  become: yes
  pacman: 
    name: rofi-wayland
    state: present
  tags: hyprland

- name: Install Screenshot tools 
  become: yes
  pacman: 
    name:
      - grimblast-git   # screenshot tool
      - slurp   # selects region for screenshot/screenshare   
      - swappy    # screenshot editor
    state: present
  tags: hyprland

- name: Install Logout Menu (wlogout)
  become: yes
  pacman:
    name: wlogout
    state: present
  tags: hyprland

# see: https://wiki.hyprland.org/Useful-Utilities/Other/#automatically-mounting-using-udiskie
- name: Setup Automatically Mounting 
  become: yes
  pacman: 
    name: udiskie
    state: present
  tags: hyprland

- name: Install Clipboard Manager
  become: yes
  pacman: 
    name: wl-clipboard
    state: present
  tags: hyprland