- name: Install Epiphany
  become: yes
  pacman:
    name: epiphany
    state: present
  tags: 
    - browser
    - epiphany

- name: Install Edge (AUR)
  become: yes
  pacman: 
    name: microsoft-edge-stable-bin
    state: present
    executable: yay 
    extra_args: --builddir /var/cache/yay
  tags: 
    - browser
    - edge