- name: Install Epiphany, Edge in Archlinux
  include_tasks: archlinux.yml
  when: ansible_distribution == "Archlinux"
  tags: 
    - browser
    - epiphany
    - edge

- name: Install Epiphany, Edge in Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: 
    - browser
    - epiphany
    - edge