- name: Install fish, starship
  become: yes
  pacman:
    name:
      - fish
      - starship
    state: present
  tags: fish

# - name: Initialize Starship prompt for fish
#   lineinfile:
#     path: ~/.config/fish/config.fish 
#     line: 'starship init fish | source'
#     state: present
#   tags: 
#     - fish 
#     - starship