- name: Optimize Battery Life (tlp)
  become: yes
  pacman: 
    name: tlp
    state: present
  tags: battery

- name: Enable TLP Service
  become: yes
  ansible.builtin.systemd:
    name: tlp
    state: started
    enabled: yes
  tags: battery

- name: Enable TLP
  become: yes
  ansible.builtin.shell: tlp start
  args:
    executable: /bin/bash
  tags: battery

- name: Detect NVIDIA GPU
  command: 'lspci | grep -i nvidia'
  register: nvidia_gpu
  ignore_errors: yes

# - name: Video Acceleration (NVIDIA)
#   become: yes
#   pacman: 
#     name: libva-nvidia-driver-git
#     state: present
#     executable: yay 
#     extra_args: --builddir /var/cache/yay
#   when: nvidia_gpu.rc == 0
#   tags: video-acceleration

# - name: Video Acceleration (Generic)
#   become: yes
#   pacman: 
#     name: libva # Video Acceleration (VA) API for Linux
#     state: present
#   when: nvidia_gpu.rc != 0
#   tags: video-acceleration